name: Practice
on: workflow_dispatch
jobs:
  workflow-1:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install node_modules
        run: npm i
      - name: Run lint
        run: npm run lint
      - name: Run build
        run: npm run build
      - name: Run tests
        run: npm run test
